import { Business, Product, Customer, Order, OrderItem, Expense, MarketingContent, AICoachMessage } from '../types';

export const NOOR_JEWELS_BUSINESS_ID = 'demo-business-noor-jewels';
export const DEMO_USER_ID = 'demo-user-noor';

export const DEMO_BUSINESS: Business = {
  id: NOOR_JEWELS_BUSINESS_ID,
  owner_id: DEMO_USER_ID,
  name: 'Noor Jewels',
  tagline: 'Timeless handcrafted fine jewelry for modern grace',
  category: 'Jewellery',
  description: 'Handcrafted fine jewelry crafted with authentic baroque pearls, recycled 18k gold vermeil, and ethical gemstones.',
  stage: 'selling',
  target_audience: 'Modern professional women & brides seeking heirloom-quality, ethical luxury pieces.',
  biggest_challenge: 'Scaling marketing while maintaining high-touch custom craftsmanship.',
  currency: 'USD',
  currency_symbol: '$',
  is_demo: true,
  created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Aura Freshwater Baroque Pearl Earrings',
    description: 'Lustrous natural organic baroque pearls suspended from hand-hammered 18k gold vermeil hoops.',
    category: 'Earrings',
    selling_price: 135.00,
    cost_price: 38.00,
    stock_quantity: 18,
    low_stock_threshold: 6,
    units_sold: 42,
    image_url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=800',
    sku: 'NJ-EAR-001',
    status: 'active',
    created_at: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Celeste Diamond Stacking Band',
    description: 'Ethically sourced lab-grown pave diamonds set in solid 14k recycled yellow gold.',
    category: 'Rings',
    selling_price: 260.00,
    cost_price: 85.00,
    stock_quantity: 8,
    low_stock_threshold: 4,
    units_sold: 28,
    image_url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800',
    sku: 'NJ-RNG-002',
    status: 'active',
    created_at: new Date(Date.now() - 48 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Soleil Chunky Link Charm Bracelet',
    description: 'Statement Italian link chain with removable mother-of-pearl talisman pendant.',
    category: 'Bracelets',
    selling_price: 185.00,
    cost_price: 52.00,
    stock_quantity: 4, // LOW STOCK!
    low_stock_threshold: 6,
    units_sold: 35,
    image_url: 'https://images.unsplash.com/photo-1611591475877-22007f3001fc?auto=format&fit=crop&q=80&w=800',
    sku: 'NJ-BRC-003',
    status: 'active',
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Seraphina Emerald Choker Pendant',
    description: 'Emerald-cut hydrothermal Colombian emerald on a fine herringbone chain.',
    category: 'Necklaces',
    selling_price: 210.00,
    cost_price: 62.00,
    stock_quantity: 12,
    low_stock_threshold: 5,
    units_sold: 19,
    image_url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800',
    sku: 'NJ-NCK-004',
    status: 'active',
    created_at: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Lumière Diamond Drop Huggies',
    description: 'Everyday mini hoop huggies with delicate floating diamond drops in 18k vermeil.',
    category: 'Earrings',
    selling_price: 120.00,
    cost_price: 34.00,
    stock_quantity: 2, // CRITICAL LOW STOCK!
    low_stock_threshold: 5,
    units_sold: 49,
    image_url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=800',
    sku: 'NJ-EAR-005',
    status: 'active',
    created_at: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Heirloom Locket Necklace',
    description: 'Hand-engraved vintage oval locket that holds two personal photographs.',
    category: 'Necklaces',
    selling_price: 175.00,
    cost_price: 48.00,
    stock_quantity: 14,
    low_stock_threshold: 5,
    units_sold: 22,
    image_url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800',
    sku: 'NJ-NCK-006',
    status: 'active',
    created_at: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-7',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Elysian Solitaire Pearl Ring',
    description: 'Single AAA grade button pearl nestled in a textured sculptural gold cup band.',
    category: 'Rings',
    selling_price: 145.00,
    cost_price: 40.00,
    stock_quantity: 16,
    low_stock_threshold: 4,
    units_sold: 17,
    image_url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&q=80&w=800',
    sku: 'NJ-RNG-007',
    status: 'active',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-8',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Symphony Tennis Bracelet',
    description: 'Continuous row of micro-faceted white topaz in a flexible 4-prong setting.',
    category: 'Bracelets',
    selling_price: 240.00,
    cost_price: 70.00,
    stock_quantity: 7,
    low_stock_threshold: 4,
    units_sold: 14,
    image_url: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&q=80&w=800',
    sku: 'NJ-BRC-008',
    status: 'active',
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-9',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Riviera Paperclip Chain 18"',
    description: 'Heavy gauge modular paperclip chain in thick 18k gold over sterling silver.',
    category: 'Necklaces',
    selling_price: 160.00,
    cost_price: 44.00,
    stock_quantity: 22,
    low_stock_threshold: 6,
    units_sold: 31,
    image_url: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&q=80&w=800',
    sku: 'NJ-NCK-009',
    status: 'active',
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-10',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Petite Opal Studs in 14k',
    description: 'Australian fire opals with kaleidoscopic rainbow flashes in classic buttercup settings.',
    category: 'Earrings',
    selling_price: 95.00,
    cost_price: 26.00,
    stock_quantity: 25,
    low_stock_threshold: 8,
    units_sold: 38,
    image_url: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&q=80&w=800',
    sku: 'NJ-EAR-010',
    status: 'active',
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-11',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Noor Heirloom Velvet Jewelry Box',
    description: 'Plush dusty rose velvet organizer with gold-brass monogram clasp for your collection.',
    category: 'Accessories',
    selling_price: 65.00,
    cost_price: 18.00,
    stock_quantity: 30,
    low_stock_threshold: 10,
    units_sold: 29,
    image_url: 'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?auto=format&fit=crop&q=80&w=800',
    sku: 'NJ-ACC-011',
    status: 'active',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-12',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Golden Radiance Signet Ring',
    description: 'Oval satin-brushed gold signet ring featuring a centered starry diamond accent.',
    category: 'Rings',
    selling_price: 195.00,
    cost_price: 55.00,
    stock_quantity: 11,
    low_stock_threshold: 4,
    units_sold: 21,
    image_url: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&q=80&w=800',
    sku: 'NJ-RNG-012',
    status: 'active',
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Sophia Laurent',
    email: 'sophia.laurent@example.com',
    phone: '+1 (555) 234-5678',
    address: '450 Mercer St, SoHo, New York, NY',
    notes: 'Loves pearls and gold vermeil. VIP repeat bridal client.',
    total_orders: 4,
    total_spent: 815.00,
    last_purchase_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cust-2',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Elena Rostova',
    email: 'elena.rostova@example.com',
    phone: '+1 (555) 890-1234',
    address: '128 Beacon St, Boston, MA',
    notes: 'Purchased anniversary gifts and custom stacking bands.',
    total_orders: 3,
    total_spent: 685.00,
    last_purchase_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cust-3',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Amina Al-Mansoor',
    email: 'amina.m@example.com',
    phone: '+1 (555) 345-6789',
    address: '772 Oakwood Dr, Chicago, IL',
    notes: 'Prefers statement earrings and emerald necklaces.',
    total_orders: 3,
    total_spent: 595.00,
    last_purchase_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cust-4',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Chloe Bennett',
    email: 'chloe.b@example.com',
    phone: '+1 (555) 678-9012',
    address: '891 Pine Terrace, San Francisco, CA',
    notes: 'Bought bridesmaids gifts in bulk.',
    total_orders: 2,
    total_spent: 540.00,
    last_purchase_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cust-5',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Maya Patel',
    email: 'maya.patel@example.com',
    phone: '+1 (555) 432-1098',
    address: '210 South Lamar Blvd, Austin, TX',
    notes: 'Stacking enthusiast. Awaiting new emerald collection.',
    total_orders: 2,
    total_spent: 405.00,
    last_purchase_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cust-6',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Isabella Rossi',
    email: 'isabella.rossi@example.com',
    phone: '+1 (555) 789-0123',
    address: '604 Sunset Blvd, Los Angeles, CA',
    notes: 'Discovered through Instagram influencer collaboration.',
    total_orders: 1,
    total_spent: 260.00,
    last_purchase_at: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cust-7',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Zoe Kensington',
    email: 'zoe.k@example.com',
    phone: '+1 (555) 567-8901',
    address: '320 Highland Ave, Seattle, WA',
    notes: 'Bought paperclip chain + velvet box.',
    total_orders: 1,
    total_spent: 225.00,
    last_purchase_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cust-8',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    name: 'Hannah Miller',
    email: 'hannah.m@example.com',
    phone: '+1 (555) 901-2345',
    address: '512 Elm St, Denver, CO',
    notes: 'Signed up at holiday pop-up market.',
    total_orders: 1,
    total_spent: 135.00,
    last_purchase_at: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const DEMO_ORDERS: Order[] = [
  {
    id: 'ord-101',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    customer_id: 'cust-1',
    customer_name: 'Sophia Laurent',
    order_number: 'NJ-1089',
    status: 'completed',
    subtotal: 395.00,
    discount: 0.00,
    tax: 0.00,
    total_amount: 395.00,
    total_cost: 123.00,
    total_profit: 272.00,
    payment_method: 'Card',
    notes: 'Gift wrap requested with handwritten note.',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-1',
        order_id: 'ord-101',
        product_id: 'prod-1',
        product_name: 'Aura Freshwater Baroque Pearl Earrings',
        quantity: 1,
        unit_price: 135.00,
        unit_cost: 38.00,
        subtotal: 135.00,
        profit: 97.00,
        created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'item-2',
        order_id: 'ord-101',
        product_id: 'prod-2',
        product_name: 'Celeste Diamond Stacking Band',
        quantity: 1,
        unit_price: 260.00,
        unit_cost: 85.00,
        subtotal: 260.00,
        profit: 175.00,
        created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      }
    ]
  },
  {
    id: 'ord-102',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    customer_id: 'cust-2',
    customer_name: 'Elena Rostova',
    order_number: 'NJ-1088',
    status: 'completed',
    subtotal: 305.00,
    discount: 0.00,
    tax: 0.00,
    total_amount: 305.00,
    total_cost: 86.00,
    total_profit: 219.00,
    payment_method: 'Card',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-3',
        order_id: 'ord-102',
        product_id: 'prod-3',
        product_name: 'Soleil Chunky Link Charm Bracelet',
        quantity: 1,
        unit_price: 185.00,
        unit_cost: 52.00,
        subtotal: 185.00,
        profit: 133.00,
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'item-4',
        order_id: 'ord-102',
        product_id: 'prod-5',
        product_name: 'Lumière Diamond Drop Huggies',
        quantity: 1,
        unit_price: 120.00,
        unit_cost: 34.00,
        subtotal: 120.00,
        profit: 86.00,
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      }
    ]
  },
  {
    id: 'ord-103',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    customer_id: 'cust-3',
    customer_name: 'Amina Al-Mansoor',
    order_number: 'NJ-1087',
    status: 'completed',
    subtotal: 345.00,
    discount: 0.00,
    tax: 0.00,
    total_amount: 345.00,
    total_cost: 100.00,
    total_profit: 245.00,
    payment_method: 'Stripe',
    created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-5',
        order_id: 'ord-103',
        product_id: 'prod-4',
        product_name: 'Seraphina Emerald Choker Pendant',
        quantity: 1,
        unit_price: 210.00,
        unit_cost: 62.00,
        subtotal: 210.00,
        profit: 148.00,
        created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'item-6',
        order_id: 'ord-103',
        product_id: 'prod-1',
        product_name: 'Aura Freshwater Baroque Pearl Earrings',
        quantity: 1,
        unit_price: 135.00,
        unit_cost: 38.00,
        subtotal: 135.00,
        profit: 97.00,
        created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
      }
    ]
  },
  {
    id: 'ord-104',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    customer_id: 'cust-4',
    customer_name: 'Chloe Bennett',
    order_number: 'NJ-1086',
    status: 'completed',
    subtotal: 270.00,
    discount: 0.00,
    tax: 0.00,
    total_amount: 270.00,
    total_cost: 76.00,
    total_profit: 194.00,
    payment_method: 'Card',
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-7',
        order_id: 'ord-104',
        product_id: 'prod-1',
        product_name: 'Aura Freshwater Baroque Pearl Earrings',
        quantity: 2,
        unit_price: 135.00,
        unit_cost: 38.00,
        subtotal: 270.00,
        profit: 194.00,
        created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      }
    ]
  },
  {
    id: 'ord-105',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    customer_id: 'cust-5',
    customer_name: 'Maya Patel',
    order_number: 'NJ-1085',
    status: 'completed',
    subtotal: 260.00,
    discount: 0.00,
    tax: 0.00,
    total_amount: 260.00,
    total_cost: 85.00,
    total_profit: 175.00,
    payment_method: 'Card',
    created_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-8',
        order_id: 'ord-105',
        product_id: 'prod-2',
        product_name: 'Celeste Diamond Stacking Band',
        quantity: 1,
        unit_price: 260.00,
        unit_cost: 85.00,
        subtotal: 260.00,
        profit: 175.00,
        created_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
      }
    ]
  },
  {
    id: 'ord-106',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    customer_id: 'cust-6',
    customer_name: 'Isabella Rossi',
    order_number: 'NJ-1084',
    status: 'completed',
    subtotal: 260.00,
    discount: 0.00,
    tax: 0.00,
    total_amount: 260.00,
    total_cost: 85.00,
    total_profit: 175.00,
    payment_method: 'Card',
    created_at: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-9',
        order_id: 'ord-106',
        product_id: 'prod-2',
        product_name: 'Celeste Diamond Stacking Band',
        quantity: 1,
        unit_price: 260.00,
        unit_cost: 85.00,
        subtotal: 260.00,
        profit: 175.00,
        created_at: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
      }
    ]
  },
  {
    id: 'ord-107',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    customer_id: 'cust-7',
    customer_name: 'Zoe Kensington',
    order_number: 'NJ-1083',
    status: 'completed',
    subtotal: 225.00,
    discount: 0.00,
    tax: 0.00,
    total_amount: 225.00,
    total_cost: 62.00,
    total_profit: 163.00,
    payment_method: 'Card',
    created_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-10',
        order_id: 'ord-107',
        product_id: 'prod-9',
        product_name: 'Riviera Paperclip Chain 18"',
        quantity: 1,
        unit_price: 160.00,
        unit_cost: 44.00,
        subtotal: 160.00,
        profit: 116.00,
        created_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'item-11',
        order_id: 'ord-107',
        product_id: 'prod-11',
        product_name: 'Noor Heirloom Velvet Jewelry Box',
        quantity: 1,
        unit_price: 65.00,
        unit_cost: 18.00,
        subtotal: 65.00,
        profit: 47.00,
        created_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
      }
    ]
  },
  {
    id: 'ord-108',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    customer_id: 'cust-8',
    customer_name: 'Hannah Miller',
    order_number: 'NJ-1082',
    status: 'completed',
    subtotal: 135.00,
    discount: 0.00,
    tax: 0.00,
    total_amount: 135.00,
    total_cost: 38.00,
    total_profit: 97.00,
    payment_method: 'Cash',
    created_at: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-12',
        order_id: 'ord-108',
        product_id: 'prod-1',
        product_name: 'Aura Freshwater Baroque Pearl Earrings',
        quantity: 1,
        unit_price: 135.00,
        unit_cost: 38.00,
        subtotal: 135.00,
        profit: 97.00,
        created_at: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
      }
    ]
  }
];

export const DEMO_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    title: 'Natural Baroque Pearls Wholesale Lot (100 pcs)',
    category: 'Materials',
    amount: 480.00,
    expense_date: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    notes: 'Grade AAA raw cultured pearls directly from artisan farm.',
    created_at: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'exp-2',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    title: 'Custom Luxury Debossed Gift Boxes & Silk Pouches',
    category: 'Packaging',
    amount: 320.00,
    expense_date: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    notes: '500 custom wine & blush branded packaging suite.',
    created_at: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'exp-3',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    title: 'Instagram & Pinterest Lifestyle Photoshoot Studio',
    category: 'Marketing',
    amount: 350.00,
    expense_date: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    notes: 'Model, props, and high-res macro jewelry photography.',
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'exp-4',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    title: 'Klaviyo Email Marketing & Shopify Pro Subscription',
    category: 'Software',
    amount: 79.00,
    expense_date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    notes: 'Monthly recurring software suite.',
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'exp-5',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    title: 'Jewelry Pop-up Booth Fee (SoHo Artisan Fair)',
    category: 'Marketing',
    amount: 220.00,
    expense_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    notes: 'Weekend table fee; generated 8 direct new client leads.',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const DEMO_MARKETING_CONTENT: MarketingContent[] = [
  {
    id: 'mkt-1',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    type: 'instagram_caption',
    title: 'Baroque Pearl Everyday Luxury Hook',
    prompt: 'Write an editorial Instagram caption for the Aura Baroque Pearl Earrings focusing on timeless sophistication.',
    content: `Organic, unrepeated, and uniquely yours. ✨\n\nNo two freshwater baroque pearls are ever identical — each curve and iridescent glow tells its own story. Suspended from 18k recycled gold vermeil hoops, the Aura Earrings move effortlessly from morning meetings to candlelight dinners.\n\nCrafted by hand in limited batches.\n\nTap the link in bio to claim your heirloom piece before our seasonal batch closes. 🕊️\n\n#NoorJewels #BaroquePearls #SlowJewelry #ModernHeirloom #QuietLuxury`,
    target_channel: 'Instagram',
    is_saved: true,
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mkt-2',
    business_id: NOOR_JEWELS_BUSINESS_ID,
    type: 'whatsapp_copy',
    title: 'VIP Bridal & Anniversary Client Message',
    prompt: 'Create a warm, personalized WhatsApp message for VIP customers announcing restock of best-selling earrings.',
    content: `Hi {FirstName}! 🌸\n\nHope your week is wonderful. As someone who appreciates our signature craftsmanship, we wanted you to be the very first to know: our beloved Aura Baroque Pearl Earrings and Celeste Bands are freshly restocked in our studio this morning!\n\nBecause each pearl is hand-selected, we only have 18 pairs available for this release.\n\nIf you'd like us to hold a pair in a personalized gift box for you, just reply to this message and we'll take care of everything.\n\nWarmly,\nThe Noor Jewels Atelier ✨`,
    target_channel: 'WhatsApp',
    is_saved: true,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const DEMO_AI_MESSAGES: AICoachMessage[] = [
  {
    id: 'msg-1',
    conversation_id: 'conv-demo-1',
    role: 'user',
    content: 'How is my business doing this month, and what should I focus on next?',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-2',
    conversation_id: 'conv-demo-1',
    role: 'assistant',
    content: `Your business **Noor Jewels** is performing exceptionally well with strong fundamentals! 🌟

Here is your executive diagnosis based on your real numbers:
- **Total Revenue**: $2,195.00 across 8 completed sales
- **Net Profit**: $1,535.00 with an outstanding **70.0% net profit margin** (well above industry average of 45-55% for luxury jewelry)
- **Top Performer**: The *Aura Freshwater Baroque Pearl Earrings* (42 units sold, $135.00 selling price with $97.00 profit per unit)

**Critical Action Items to Focus on Today:**
1. ⚠️ **Restock Alert**: *Lumière Diamond Drop Huggies* has only **2 units left**, and *Soleil Charm Bracelet* has **4 units left**. Both are high-demand items that will stock out within 7-10 days at current velocity.
2. 💎 **VIP Retention**: You have 8 loyal customers, and Sophia Laurent is leading with $815.00 in lifetime spend across 4 orders. Sending a handwritten note or VIP preview will maximize her lifetime value.
3. 📈 **Bundle Opportunity**: Consider bundling the *Aura Pearl Earrings* + *Velvet Jewelry Box* as a "Gift of Elegance" set for a $180 price point to increase your average order value from $274 to $320+.`,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 4000).toISOString(),
  }
];
